[colors]
foreground = "#cccccc"
background = "#1e1e1e"
cursor_bg = "#cccccc"
cursor_border = "#cccccc"
cursor_fg = "#1e1e1e"
selection_bg = "#264F78"
selection_fg = "#e5e5e5"

ansi = [
  "#1e1e1e",
  "#cd3131",
  "#0dbc79",
  "#e5e510",
  "#2472c8",
  "#bc3fbc",
  "#11a8cd",
  "#e5e5e5"
]

brights = [
  "#666666",
  "#f14c4c",
  "#23d18b",
  "#f5f543",
  "#3b8eea",
  "#d670d6",
  "#29b8db",
  "#e5e5e5"
]

[colors.tab_bar]
background = "#1e1e1e"

[colors.tab_bar.active_tab]
bg_color = "#1e1e1e"
fg_color = "#cccccc"
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = "#373737"
fg_color = "#cccccc"
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = "#373737"
fg_color = "#cccccc"
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
name = 'Dark+'